In [1]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv("/content/dataset_Facebook.csv",delimiter=';')

In [20]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [21]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [22]:
df=df.dropna()

In [23]:
#subset data

In [24]:
df_sub1=df[['Type','Category','comment','like']]

In [26]:
df_sub1.head()

     Type  Category  comment    like
0   Photo         2        4    79.0
1  Status         2        5   130.0
2   Photo         3        0    66.0
3   Photo         2       58  1572.0
4   Photo         2       19   325.0

In [34]:
df_sub2=df[(df['like']>100) & (df['comment']>20)]

In [35]:
df_sub2[['Type','like','comment']].head()

      Type    like  comment
3    Photo  1572.0       58
28   Photo   523.0       36
30   Photo   107.0       33
51   Photo   285.0       24
101  Photo  1505.0       26

In [44]:
df_sub3=df[(df['Type']=='Video') | (df['Type']=='Photo')]
df_sub3.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [36]:
#merge data

In [38]:
df_1=df[['Type','like','share']]
df_2=df[['Type','comment']]
df_merge=pd.merge(df_1,df_2,on='Type')

In [40]:
df_merge.head()

    Type  like  share  comment
0  Photo  79.0   17.0        4
1  Photo  79.0   17.0        0
2  Photo  79.0   17.0       58
3  Photo  79.0   17.0       19
4  Photo  79.0   17.0        3

In [45]:
#sorting

In [46]:
df_desc=df.sort_values(by='like',ascending=False)
df_desc.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777

In [48]:
df_asc=df.sort_values(by='comment',ascending=True)
df_asc.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18

In [49]:
#transpose

In [50]:
df_t=df.T
df_t.head()

,0,1,2,3,4,5,6,7,8,9,...,489,490,491,492,493,494,495,496,497,498
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85979,85093,85093,85093,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,3,1,3,3,3,2,1,3
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,7,6,6,5,1,7,7,5,5,4

In [51]:
#shape reshape

In [53]:
df.shape

(495, 19)

In [65]:
df_pivo=pd.pivot_table(df,index='Type',columns='Category',values='comment')
df_pivo

Category          1          2         3
Type
Link       2.900000   2.000000  2.000000
Photo      6.027624  11.822222  6.913333
Status     4.333333   9.921053  2.750000
Video     12.285714        NaN       NaN

In [62]:
df['Category'].value_counts()

Category
1    211
3    155
2    129
Name: count, dtype: int64

In [63]:
reshape_df = pd.melt(
    df[['Type', 'Category', 'share']],
    id_vars=['Type'],
    var_name='Attribute',
    value_name='Value'
)

In [64]:
reshape_df.head()

     Type Attribute  Value
0   Photo  Category    2.0
1  Status  Category    2.0
2   Photo  Category    3.0
3   Photo  Category    2.0
4   Photo  Category    2.0